baseURL = "http://example.org/"
languageCode = "en-us"
title = "張晶"
theme = "hugo-ivy"
disqusShortname = "zhangakira"
[menu]
[[menu.main]]
  identifier = 'blog'
  name = '日志'
  title = 'blog section'
  url = '/cn/daily/'
  weight = -110
[[menu.main]]
  identifier = 'archive'
  name = '諤ｻ扈錀'
  title = 'blog section'
  url = '/cn/summary/'
  weight = -100
[[menu.main]]
  identifier = 'menu'
  name = '菜隹ｱ'
  title = 'blog section'
  url = '/cn/menu/'
  weight = -100
[[menu.main]]
  identifier = 'about'
  name = "蜈ｳ于"
  title = 'blog section'
  url = '/cn/about/'
  weight = -11
[params]
footer = "&copy; [Jing Zhang](/) 2010 - 2021"
[params.logo.en]
img = "/images/logo.png"
url = "/"
alt = "Jing Zhang"
tag = ""